services:
  postgres:
    image: postgres:16
    container_name: plumberlama-postgres
    environment:
      POSTGRES_USER: plumberlama
      POSTGRES_PASSWORD: plumberlama_dev
      POSTGRES_DB: survey_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plumberlama -d survey_data"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - plumberlama

  # initialize site_output volume with correct permissions for nonroot user (UID 999)
  init-volume:
    image: alpine:latest
    container_name: plumberlama-init-volume
    volumes:
      - site_output:/app/site
    command: sh -c "chown -R 999:999 /app/site && chmod -R 755 /app/site && echo 'Volume permissions set for UID 999'"
    networks:
      - plumberlama

  pipeline:
    build: .
    image: plumberlama:latest
    container_name: plumberlama-pipeline
    env_file:
      - .env
    user: "999:999"
    environment:
      # Database connection (override if needed)
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: survey_data
      DB_USER: plumberlama
      DB_PASSWORD: plumberlama_dev
      # Output directory - site will be built in /app/site
      SITE_OUTPUT_DIR: /app/site
    volumes:
      # Mount site output directory for web server
      - site_output:/app/site
    depends_on:
      init-volume:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    networks:
      - plumberlama

  web:
    image: nginx:alpine
    container_name: plumberlama-web
    ports:
      - "8080:80"
    volumes:
      - site_output:/usr/share/nginx/html:ro
    environment:
      # Nginx will use default config which serves from /usr/share/nginx/html
      NGINX_HOST: localhost
      NGINX_PORT: 80
    depends_on:
      - pipeline
    networks:
      - plumberlama
    restart: unless-stopped

volumes:
  postgres_data:
  site_output:

networks:
  plumberlama:
    driver: bridge
