services:
  postgres:
    image: postgres:16
    container_name: plumberlama-postgres
    environment:
      POSTGRES_USER: plumberlama
      POSTGRES_PASSWORD: plumberlama_dev
      POSTGRES_DB: survey_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plumberlama"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
